services:
  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: ansh
      RABBITMQ_DEFAULT_PASS: ansh@2004
    ports:
      - "5672:5672"
      - "15672:15672"

  user-service:
    build: ./user
    env_file:
      - ./user/.env
    depends_on:
      - rabbitmq

  mail-service:
    build: ./mail
    env_file:
      - ./mail/.env
    depends_on:
      - rabbitmq
